#include <"debug.h">

void writeVtkDebug(const double * const collideField,
    const int * const flagField, const char * filename, int xlength)
{
    // Files related variables
    char pFileName[80];
    FILE *fp = NULL;

    // Create the file with time information in the name
    sprintf(pFileName, "%s.vtk", filename);
    fp  = fopen(pFileName, "w");

    // Check if files were opened or not
    if(fp == NULL)
    {
        char szBuff[80];
        sprintf(szBuff, "Failed to open %s", pFileName);
        ERROR(szBuff);
        return;
    }

    // Write header for the VTK file
    writevtkHeaderDebug(fp, xlength);

    // Write the point data for the domain
    writevtkPointCoordinatesDebug(fp, xlength);

    // iteration variables
    int x, y, z;

    fprintf(fp,"\nCELL_DATA %d \n", (xlength[0]+2)*(xlength[1]+2)*(xlength[2]+2));

    // Write cell average density to a temporary vtk file
    fprintf(fp, "SCALARS boundaryType integer 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");
    for(z = 0; z <= xlength+1; z++) {
        for(y = 0; y <= xlength+1; y++) {
            for(x = 0; x <= xlength+1; x++) {
                // Compute the base index for collideField
                int xyzoffset = z*(xlength+2)*(xlength+2) + y*(xlength+2) + x;
                fprintf(fp, "%d\n", flagField[xyzoffset]);
            }
        }
    }
    // Close files
    if(fclose(fp))
    {
        char szBuff[80];
        sprintf(szBuff, "Failed to close %s", pFileName);
        ERROR(szBuff);
    }
}

void writevtkHeaderDebug(FILE *fp, int xlength)
{
    if(fp == NULL)
    {
        char szBuff[80];
        sprintf(szBuff, "Null pointer in write_vtkHeader");
        ERROR(szBuff);
        return;
    }

    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"generated by CFD-lab course output (written by Vishal Sontakke) \n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");
    fprintf(fp,"DATASET STRUCTURED_GRID\n");
    fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength+3, xlength+3, xlength+3);
    fprintf(fp,"POINTS %i integer\n", (xlength+3)*(xlength+3)*(xlength+3));
    fprintf(fp,"\n");
}

void writevtkPointCoordinatesDebug(FILE *fp, int xlength) {
    int x, y, z;

    // We have xlength + 3 points for xlength+2 cells in each direction
    for(z = 0; z <= xlength+2; z++) {
        for(y = 0; y <= xlength+2; y++) {
            for(x = 0; x <= xlength+2; x++) {
                fprintf(fp, "%d %d %d\n", x, y, z);
            }
        }
    }
}
